### ISSUE TITLE
[BUG] Not able to run Webtop behind Apache Reverse-Proxy

### ISSUE THREAD

**Issue by felix-sterzelmaier-concat** [linuxserver/docker-baseimage-kasmvnc#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am running a server in my local network which has many services running in docker. I want to add Webtop:ubuntu-mate to these services. Here is my Docker-Compose File:

```
version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-mate
    container_name: webtop
    #security_opt:
    #  - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
      - CUSTOM_USER=xxx
      - PASSWORD=xxx
    volumes:
      - /data/webtop2/data:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 8007:3000
      - 8008:3001
    #devices:
    #  - /dev/dri:/dev/dri #optional
    shm_size: "4gb" #optional
    restart: unless-stopped
```

From my client in my local network i am Able to reach http://192.168.178.75:8007/ and https://192.168.178.75:8008/. Everything is working fine so far. Now i want to make this service available behind a reverse proxy. I used the documentation here: https://kasmweb.com/docs/latest/how_to/reverse_proxy.html#example-apache-config
This is my Apache config:

```
<VirtualHost *:443>
    ServerName xxx
    # SSL
    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/live/xxx/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/xxx/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf
    # Websocket upgrade
    RewriteEngine on
    RewriteCond ${HTTP:Upgrade} websocket [NC]
    RewriteCond ${HTTP:Connection} upgrade [NC]
    RewriteRule .* "wss://127.0.0.1:8008/$1" [P,L]
    # Proxy
    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off
    ProxyPreserveHost on
    ProxyPass / https://127.0.0.1:8008/
    ProxyPassReverse / https://127.0.0.1:8008/
    ProxyRequests off
</VirtualHost>
```

The Documentation also mentions i should "Update Zones" in "Kasm Workspaces UI". How can i do this? How can i reach the Administrator UI?

I have a DNS-Record to my router which is forwarded (using NAT) to the docker host. Let's assume the DNS-Record is example.com. When opening https://example.com i see this:

![a](https://github.com/linuxserver/docker-baseimage-kasmvnc/assets/148772869/483c0a1d-c60e-4756-9a1b-7ef0c69c0646)
![b](https://github.com/linuxserver/docker-baseimage-kasmvnc/assets/148772869/6ec78905-ab7f-4e77-850e-e67b8c22bc78)

![c](https://github.com/linuxserver/docker-baseimage-kasmvnc/assets/148772869/8f8f213b-0fa8-4c2f-a80a-73731aff52b2)

### Expected Behavior

The Desktop should be visible.

### Steps To Reproduce

see Current Behavior

### Environment

```markdown
- OS: Ubuntu Server 22.04 LTS 64bit
- How docker service was installed: see Current Behavior
```

### Docker creation

```bash
see Current Behavior
```

### Container logs

```bash
probably not relevant
```
